In [2]:
%pip install numpy
import numpy as np
lista = [1,2,3,4,5,6]
array = np.array(lista)
array2 = np.arange(start = 2, stop = 10, step = 1)
print(array,array2)


[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
[1 2 3 4 5 6] [2 3 4 5 6 7 8 9]


In [3]:
arr = np.linspace(start = 1,stop = 90, num = 100)
print(arr)

[ 1.          1.8989899   2.7979798   3.6969697   4.5959596   5.49494949
  6.39393939  7.29292929  8.19191919  9.09090909  9.98989899 10.88888889
 11.78787879 12.68686869 13.58585859 14.48484848 15.38383838 16.28282828
 17.18181818 18.08080808 18.97979798 19.87878788 20.77777778 21.67676768
 22.57575758 23.47474747 24.37373737 25.27272727 26.17171717 27.07070707
 27.96969697 28.86868687 29.76767677 30.66666667 31.56565657 32.46464646
 33.36363636 34.26262626 35.16161616 36.06060606 36.95959596 37.85858586
 38.75757576 39.65656566 40.55555556 41.45454545 42.35353535 43.25252525
 44.15151515 45.05050505 45.94949495 46.84848485 47.74747475 48.64646465
 49.54545455 50.44444444 51.34343434 52.24242424 53.14141414 54.04040404
 54.93939394 55.83838384 56.73737374 57.63636364 58.53535354 59.43434343
 60.33333333 61.23232323 62.13131313 63.03030303 63.92929293 64.82828283
 65.72727273 66.62626263 67.52525253 68.42424242 69.32323232 70.22222222
 71.12121212 72.02020202 72.91919192 73.81818182 74

In [4]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
arr = np.full(shape=(4,2), full_value= 2)
print(arr)

TypeError: full() got an unexpected keyword argument 'full_value'

In [12]:
base = np.full(shape = (3,6), fill_value= 4.41)
print(np.full_like(base,5))

[[5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]]


In [13]:
#Crear array con numeros aleatorios
np.random.rand(4,2)


array([[0.31504937, 0.64143715],
       [0.47030545, 0.90760777],
       [0.44075615, 0.63049182],
       [0.08048321, 0.3712616 ]])

In [14]:
arr = np.random.uniform(len = 0,high=4,size=(4,4))

TypeError: uniform() got an unexpected keyword argument 'len'

In [81]:
np.random.rand(5,5)

array([[0.93178896, 0.41648509, 0.88062169, 0.04009287, 0.85042297],
       [0.5703474 , 0.65370645, 0.73380001, 0.58962707, 0.22171597],
       [0.12413383, 0.32910392, 0.47013847, 0.81606966, 0.20352798],
       [0.23467115, 0.3917764 , 0.93142014, 0.21068699, 0.84013694],
       [0.17678272, 0.66867056, 0.76493656, 0.07488871, 0.38402817]])

In [17]:
np.random.normal(loc= 5,scale=1,size=6)

array([6.30905928, 4.17730584, 7.66681801, 5.94688752, 5.16213905,
       2.89522996])

In [18]:
arr = np.zeros(9)
print(arr.shape)

(9,)


In [20]:
b = np.reshape(arr,[3,3])
print(b)
print(b.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)


In [26]:
matrix = np.arange(16).reshape(4,4)
print(matrix)
print(matrix[0,1])
print(matrix[1,1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
1
5


In [28]:
print(matrix[:,2])

[ 2  6 10 14]


In [30]:
#copiar una matrix
matrixb = matrix.copy()
print(id(matrix))
print(id(matrixb))

5034154320
4475144016


In [34]:
#Operaciones con arrays
a = np.arange(5,10)
print(a)
print(a - 10)
print(a +  5)

[5 6 7 8 9]
[-5 -4 -3 -2 -1]
[10 11 12 13 14]


In [38]:
a = np.full(3,3)
c = np.ones(3,dtype="int")
print(a)
print(c)
print(a + c)

[3 3 3]
[1 1 1]
[4 4 4]


In [40]:
#Multiplicaciones 

print(np.matmul(a,c))

9


In [42]:
A = np.array([[2,3],[2,3],[2,3]])
B = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(A.shape)
print(B.shape)

print(np.matmul(A,B))

(3, 2)
(2, 5)
[[20 25 30 35 40]
 [20 25 30 35 40]
 [20 25 30 35 40]]


In [43]:
print(A)
print('*'*10)
print(A.T)

[[2 3]
 [2 3]
 [2 3]]
**********
[[2 2 2]
 [3 3 3]]


In [50]:
#ESTADISTICA ********
lista = [i for i in range(4,99,2)]
#print(lista)
print(np.mean(lista))
print(np.median(lista))
print(np.std(lista))
print(np.percentile(lista,q=90))
print(np.exp(lista))

51.0
51.0
27.70679820308847
88.60000000000001
[5.45981500e+01 4.03428793e+02 2.98095799e+03 2.20264658e+04
 1.62754791e+05 1.20260428e+06 8.88611052e+06 6.56599691e+07
 4.85165195e+08 3.58491285e+09 2.64891221e+10 1.95729609e+11
 1.44625706e+12 1.06864746e+13 7.89629602e+13 5.83461743e+14
 4.31123155e+15 3.18559318e+16 2.35385267e+17 1.73927494e+18
 1.28516001e+19 9.49611942e+19 7.01673591e+20 5.18470553e+21
 3.83100800e+22 2.83075330e+23 2.09165950e+24 1.54553894e+25
 1.14200739e+26 8.43835667e+26 6.23514908e+27 4.60718663e+28
 3.40427605e+29 2.51543867e+30 1.85867175e+31 1.37338298e+32
 1.01480039e+33 7.49841700e+33 5.54062238e+34 4.09399696e+35
 3.02507732e+36 2.23524660e+37 1.65163625e+38 1.22040329e+39
 9.01762841e+39 6.66317622e+40 4.92345829e+41 3.63797095e+42]


In [53]:
print(np.log(lista))
print('-' * 10)
print(np.sqrt(lista))

[1.38629436 1.79175947 2.07944154 2.30258509 2.48490665 2.63905733
 2.77258872 2.89037176 2.99573227 3.09104245 3.17805383 3.25809654
 3.33220451 3.40119738 3.4657359  3.52636052 3.58351894 3.63758616
 3.68887945 3.73766962 3.78418963 3.8286414  3.87120101 3.91202301
 3.95124372 3.98898405 4.02535169 4.06044301 4.09434456 4.12713439
 4.15888308 4.18965474 4.21950771 4.24849524 4.27666612 4.30406509
 4.33073334 4.35670883 4.38202663 4.40671925 4.4308168  4.4543473
 4.47733681 4.49980967 4.52178858 4.54329478 4.56434819 4.58496748]
----------
[2.         2.44948974 2.82842712 3.16227766 3.46410162 3.74165739
 4.         4.24264069 4.47213595 4.69041576 4.89897949 5.09901951
 5.29150262 5.47722558 5.65685425 5.83095189 6.         6.164414
 6.32455532 6.4807407  6.63324958 6.78232998 6.92820323 7.07106781
 7.21110255 7.34846923 7.48331477 7.61577311 7.74596669 7.87400787
 8.         8.1240384  8.24621125 8.36660027 8.48528137 8.60232527
 8.71779789 8.83176087 8.94427191 9.05538514 9.165151

In [55]:
a = np.random.uniform(low= 1.9, heigth = 2.0, size = 12)
b = np.random.uniform(low= 1.4, heigth = 2.0, size = 12)
print(a)
print(b)

TypeError: uniform() got an unexpected keyword argument 'heigth'

In [65]:
#Mascaras
a = np.arange(0,20).reshape(2,10)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [92]:
mask = ([a % 2] == 0)
print([a % 2 == 0])

[array([[ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False]])]


In [72]:
array = np.arange(start=1,stop=20,step = 2)
print(array)
array.shape

[ 1  3  5  7  9 11 13 15 17 19]


(10,)

In [80]:
array = np.full(shape=(4,4,4),fill_value= 6)
print(array.ndim)
print(array)

3
[[[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]

 [[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]

 [[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]

 [[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]]


In [79]:
array[2,2,2]

6

In [84]:
array = np.random.rand(5,5)
print(array)
numbers = 0
between = 0
array = np.random.rand(number,between)


[[0.36841993 0.52423909 0.91945999 0.98166775 0.56797478]
 [0.90415934 0.78027005 0.9542214  0.30715203 0.15904079]
 [0.48936067 0.74331228 0.70773832 0.811435   0.31803523]
 [0.27726096 0.15672202 0.47439508 0.42886649 0.08414993]
 [0.06582664 0.64230793 0.24063856 0.32329842 0.36201645]]


In [91]:
array[2,2]

0.707738321299472

In [103]:
a = np.arange(1,10)
b = np.arange(2,11)

c = np.where(a == b)
print(c)



(array([], dtype=int64),)


In [105]:
a = np.arange(15)

index = np.where((a >= 5) & (a <= 10))
index

(array([ 5,  6,  7,  8,  9, 10]),)

In [108]:
a = np.arange(15)
print(np.mean(a))
a[(a > 4) & (a < 11 )]

7.0


array([ 5,  6,  7,  8,  9, 10])

In [111]:
import numpy as np
array = np.array([1,2,3,4])
array.dtype

dtype('int64')

In [112]:
import numpy as np
array = np.array([1,2,3,4], dtype = "float64")
array.dtype

dtype('float64')

In [122]:
array = np.array([1,2,3,4]).reshape(2,2)
print(array.shape)#Saber la cantidad de datos del arreglo
print(array.ndim)#Saber la dimension del arreglo

(2, 2)
2


In [123]:
array = np.array([1,2,3,4], ndmin= 10)
print(array)

[[[[[[[[[[1 2 3 4]]]]]]]]]]


In [124]:
array = np.array([1,2,3,4])
np.expand_dims(array,axis=0)

array([[1, 2, 3, 4]])

In [126]:
array = np.array([1,2,3,4,5],ndmin= 4) #Tensor
print(array)
print(np.squeeze(array)) #Reduce al numero de dimensiones utiles

[[[[1 2 3 4 5]]]]
[1 2 3 4 5]


In [136]:
array = np.array([[[1,2,3],[1,2,3],[2,4,6]]],ndmin= 6)
print(array.ndim)
print(array)
print(np.squeeze(array))

6
[[[[[[1 2 3]
     [1 2 3]
     [2 4 6]]]]]]
[[1 2 3]
 [1 2 3]
 [2 4 6]]


In [139]:
#Creando arrays

np.random.rand(10)
np.linspace(start=1,stop=100,num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [140]:

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [146]:
array = np.random.rand(4,4)
print(array)
print(array[:,2])

[[0.0049433  0.96209754 0.02299743 0.29735579]
 [0.62508979 0.85358616 0.34586771 0.03765247]
 [0.96376821 0.47995623 0.45014178 0.61734945]
 [0.2722079  0.64041451 0.67292721 0.98772568]]
[0.02299743 0.34586771 0.45014178 0.67292721]


In [155]:
#Shape y Reshape

arr = np.random.randint(1,10,(3,2)).reshape((2,3))
print(arr)
print(np.reshape(arr,(3,2)))


[[7 3 4]
 [9 9 3]]
[[7 3]
 [4 9]
 [9 3]]


In [156]:
import numpy as np


In [163]:
arr = np.random.randint(1,20,10)

matrix = arr.reshape(2,5)
print(matrix)
print(matrix.argmax())

[[12 19 11 11 19]
 [19  4  8 17 19]]
1


In [164]:
arr.ptp()

15

In [166]:
arreglo = np.array([1,2,3,4,5])
arreglo2 = arreglo.copy()
print(id(arreglo))   #Tienen id diferente
print(id(arreglo2))

5038288176
5038287408


In [167]:
arreglo[:] = 100
print(arreglo)
print(arreglo2)

[100 100 100 100 100]
[1 2 3 4 5]


In [169]:
#Condiciones >> Retornar aspectos especificos

array = np.linspace(1,10,10,dtype="int8")
array



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [173]:
indices = array[array > 5]
indices

array([ 6,  7,  8,  9, 10], dtype=int8)

In [176]:
array[(array > 5 ) & (array < 8)] = 10
array

array([ 1,  2,  3,  4,  5, 10, 10,  8,  9, 10], dtype=int8)

In [183]:
array1 = np.array([1,2,3,4,5,6])
array2 = array1.copy()
array2 + 2


array([3, 4, 5, 6, 7, 8])

In [180]:
array1 * array2

array([ 1,  4,  9, 16, 25])

In [185]:
matriz = array1.reshape(2,3)
print(matriz)

[[1 2 3]
 [4 5 6]]
